#!/usr/bin/perl
use warnings;
use strict;
chomp(my$fileName=<STDIN>);
open DATA,"<$fileName";
open TEMP,"> temp";
while(<DATA>)
{
    
    s(\d+\.)();
    print $_;
    print TEMP $_;
}
close DATA;
close TEMP;

`mv temp $fileName`;



