#!/usr/bin/perl
use warnings;
use strict;

while(<>)
{
    chomp;
 if(/(\w*a)(\s.{0,4})/)
 {
 
    print "'".$1."'\n";
    print "'".$2."'\n";
    
    
 }
 else
 {
    print "No matched:$_\n";
 }
}


