#!/usr/bin/perl
##Copyright 2012 by lexEdge

use warnings;
use strict;


chomp(my$pattern=<STDIN>);
while(<>)
{
  chomp;
  if(/$pattern/)
  {
    print "it matched:$`<$&>$'\n";
  } 
  else
  {
    print "no matched!\n";
  }
}

