#!/usr/bin/perl
use warnings;
use strict;
$_="he is going out with barney tonight!\n";
s/barney/devil/;
print $_;
s/with (\w+)/against $1/;
print $_;

$_="green scaly dinosaur\n";
print $_;
s/(\w+) (\w+)/$2,$1/;
print $_;





