#!/usr/bin/perl
use warnings;
use strict;
$_="he is going out with barney tonight!\n";
s/barney/devil/;
print $_;
s/with (\w+)/against $1/;
print $_;

$_="green scaly dinosaur\n";
print $_;
s/(\w+) (\w+)/$2,$1/;
print $_;
s/^/huge,/;
print $_;
s/,.*een//;
print $_;

s/\w+$/($`!)$&/;
print $_;

s/\s+(!\W+)/$1 /;
print $_;

s/huge/giant/;
print $_;

$_="fred flintstone";
if(s/fred/wilma/)
{
print "sucessfully replaced fred with wilma\n";
}
